// Generated by Dagger (https://dagger.dev).
package com.mut_jaeryo.data.source.keyword.local;

import android.content.Context;
import com.mut_jaeryo.data.db.KeywordFactory;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LocalKeywordDataSource_Factory implements Factory<LocalKeywordDataSource> {
  private final Provider<Context> contextProvider;

  private final Provider<KeywordFactory> keywordModelProvider;

  public LocalKeywordDataSource_Factory(Provider<Context> contextProvider,
      Provider<KeywordFactory> keywordModelProvider) {
    this.contextProvider = contextProvider;
    this.keywordModelProvider = keywordModelProvider;
  }

  @Override
  public LocalKeywordDataSource get() {
    return newInstance(contextProvider.get(), keywordModelProvider.get());
  }

  public static LocalKeywordDataSource_Factory create(Provider<Context> contextProvider,
      Provider<KeywordFactory> keywordModelProvider) {
    return new LocalKeywordDataSource_Factory(contextProvider, keywordModelProvider);
  }

  public static LocalKeywordDataSource newInstance(Context context, KeywordFactory keywordModel) {
    return new LocalKeywordDataSource(context, keywordModel);
  }
}
