// Generated by Dagger (https://dagger.dev).
package com.mut_jaeryo.data.api.drawing;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class FirebaseDrawingServiceImpl_Factory implements Factory<FirebaseDrawingServiceImpl> {
  private final Provider<Context> contextProvider;

  public FirebaseDrawingServiceImpl_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public FirebaseDrawingServiceImpl get() {
    return newInstance(contextProvider.get());
  }

  public static FirebaseDrawingServiceImpl_Factory create(Provider<Context> contextProvider) {
    return new FirebaseDrawingServiceImpl_Factory(contextProvider);
  }

  public static FirebaseDrawingServiceImpl newInstance(Context context) {
    return new FirebaseDrawingServiceImpl(context);
  }
}
